// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// StakesColumns holds the columns for the "stakes" table.
	StakesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "amount", Type: field.TypeInt},
		{Name: "stock_stakes", Type: field.TypeInt},
		{Name: "user_stakes", Type: field.TypeUUID},
	}
	// StakesTable holds the schema information for the "stakes" table.
	StakesTable = &schema.Table{
		Name:       "stakes",
		Columns:    StakesColumns,
		PrimaryKey: []*schema.Column{StakesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "stakes_stocks_stakes",
				Columns:    []*schema.Column{StakesColumns[2]},
				RefColumns: []*schema.Column{StocksColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "stakes_users_stakes",
				Columns:    []*schema.Column{StakesColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// StocksColumns holds the columns for the "stocks" table.
	StocksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "channel_id", Type: field.TypeString, Unique: true},
		{Name: "symbol", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "activity", Type: field.TypeJSON, Nullable: true},
	}
	// StocksTable holds the schema information for the "stocks" table.
	StocksTable = &schema.Table{
		Name:       "stocks",
		Columns:    StocksColumns,
		PrimaryKey: []*schema.Column{StocksColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "slack_id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		StakesTable,
		StocksTable,
		UsersTable,
	}
)

func init() {
	StakesTable.ForeignKeys[0].RefTable = StocksTable
	StakesTable.ForeignKeys[1].RefTable = UsersTable
}
