// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/kkrishguptaa/whitestone-capital/apps/api/ent/schema"
	"github.com/kkrishguptaa/whitestone-capital/apps/api/ent/stake"
	"github.com/kkrishguptaa/whitestone-capital/apps/api/ent/stock"
	"github.com/kkrishguptaa/whitestone-capital/apps/api/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	stakeFields := schema.Stake{}.Fields()
	_ = stakeFields
	// stakeDescAmount is the schema descriptor for amount field.
	stakeDescAmount := stakeFields[0].Descriptor()
	// stake.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	stake.AmountValidator = stakeDescAmount.Validators[0].(func(int) error)
	stockFields := schema.Stock{}.Fields()
	_ = stockFields
	// stockDescChannelID is the schema descriptor for channel_id field.
	stockDescChannelID := stockFields[0].Descriptor()
	// stock.ChannelIDValidator is a validator for the "channel_id" field. It is called by the builders before save.
	stock.ChannelIDValidator = stockDescChannelID.Validators[0].(func(string) error)
	// stockDescSymbol is the schema descriptor for symbol field.
	stockDescSymbol := stockFields[1].Descriptor()
	// stock.SymbolValidator is a validator for the "symbol" field. It is called by the builders before save.
	stock.SymbolValidator = stockDescSymbol.Validators[0].(func(string) error)
	// stockDescName is the schema descriptor for name field.
	stockDescName := stockFields[2].Descriptor()
	// stock.NameValidator is a validator for the "name" field. It is called by the builders before save.
	stock.NameValidator = stockDescName.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescSlackID is the schema descriptor for slack_id field.
	userDescSlackID := userFields[1].Descriptor()
	// user.SlackIDValidator is a validator for the "slack_id" field. It is called by the builders before save.
	user.SlackIDValidator = userDescSlackID.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[2].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
}
