// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kkrishguptaa/whitestone-capital/apps/api/ent/stake"
	"github.com/kkrishguptaa/whitestone-capital/apps/api/ent/stock"
	"github.com/kkrishguptaa/whitestone-capital/apps/api/ent/user"
)

// StakeCreate is the builder for creating a Stake entity.
type StakeCreate struct {
	config
	mutation *StakeMutation
	hooks    []Hook
}

// SetAmount sets the "amount" field.
func (sc *StakeCreate) SetAmount(i int) *StakeCreate {
	sc.mutation.SetAmount(i)
	return sc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (sc *StakeCreate) SetUserID(id uuid.UUID) *StakeCreate {
	sc.mutation.SetUserID(id)
	return sc
}

// SetUser sets the "user" edge to the User entity.
func (sc *StakeCreate) SetUser(u *User) *StakeCreate {
	return sc.SetUserID(u.ID)
}

// SetStockID sets the "stock" edge to the Stock entity by ID.
func (sc *StakeCreate) SetStockID(id int) *StakeCreate {
	sc.mutation.SetStockID(id)
	return sc
}

// SetStock sets the "stock" edge to the Stock entity.
func (sc *StakeCreate) SetStock(s *Stock) *StakeCreate {
	return sc.SetStockID(s.ID)
}

// Mutation returns the StakeMutation object of the builder.
func (sc *StakeCreate) Mutation() *StakeMutation {
	return sc.mutation
}

// Save creates the Stake in the database.
func (sc *StakeCreate) Save(ctx context.Context) (*Stake, error) {
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *StakeCreate) SaveX(ctx context.Context) *Stake {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *StakeCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *StakeCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *StakeCreate) check() error {
	if _, ok := sc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Stake.amount"`)}
	}
	if v, ok := sc.mutation.Amount(); ok {
		if err := stake.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Stake.amount": %w`, err)}
		}
	}
	if len(sc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Stake.user"`)}
	}
	if len(sc.mutation.StockIDs()) == 0 {
		return &ValidationError{Name: "stock", err: errors.New(`ent: missing required edge "Stake.stock"`)}
	}
	return nil
}

func (sc *StakeCreate) sqlSave(ctx context.Context) (*Stake, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *StakeCreate) createSpec() (*Stake, *sqlgraph.CreateSpec) {
	var (
		_node = &Stake{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(stake.Table, sqlgraph.NewFieldSpec(stake.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.Amount(); ok {
		_spec.SetField(stake.FieldAmount, field.TypeInt, value)
		_node.Amount = value
	}
	if nodes := sc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stake.UserTable,
			Columns: []string{stake.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_stakes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.StockIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stake.StockTable,
			Columns: []string{stake.StockColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stock.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.stock_stakes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StakeCreateBulk is the builder for creating many Stake entities in bulk.
type StakeCreateBulk struct {
	config
	err      error
	builders []*StakeCreate
}

// Save creates the Stake entities in the database.
func (scb *StakeCreateBulk) Save(ctx context.Context) ([]*Stake, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Stake, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StakeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *StakeCreateBulk) SaveX(ctx context.Context) []*Stake {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *StakeCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *StakeCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
