// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kkrishguptaa/whitestone-capital/apps/api/ent/predicate"
	"github.com/kkrishguptaa/whitestone-capital/apps/api/ent/stake"
	"github.com/kkrishguptaa/whitestone-capital/apps/api/ent/stock"
)

// StockQuery is the builder for querying Stock entities.
type StockQuery struct {
	config
	ctx        *QueryContext
	order      []stock.OrderOption
	inters     []Interceptor
	predicates []predicate.Stock
	withStakes *StakeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StockQuery builder.
func (sq *StockQuery) Where(ps ...predicate.Stock) *StockQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit the number of records to be returned by this query.
func (sq *StockQuery) Limit(limit int) *StockQuery {
	sq.ctx.Limit = &limit
	return sq
}

// Offset to start from.
func (sq *StockQuery) Offset(offset int) *StockQuery {
	sq.ctx.Offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *StockQuery) Unique(unique bool) *StockQuery {
	sq.ctx.Unique = &unique
	return sq
}

// Order specifies how the records should be ordered.
func (sq *StockQuery) Order(o ...stock.OrderOption) *StockQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QueryStakes chains the current query on the "stakes" edge.
func (sq *StockQuery) QueryStakes() *StakeQuery {
	query := (&StakeClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stock.Table, stock.FieldID, selector),
			sqlgraph.To(stake.Table, stake.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, stock.StakesTable, stock.StakesColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Stock entity from the query.
// Returns a *NotFoundError when no Stock was found.
func (sq *StockQuery) First(ctx context.Context) (*Stock, error) {
	nodes, err := sq.Limit(1).All(setContextOp(ctx, sq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{stock.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *StockQuery) FirstX(ctx context.Context) *Stock {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Stock ID from the query.
// Returns a *NotFoundError when no Stock ID was found.
func (sq *StockQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(1).IDs(setContextOp(ctx, sq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{stock.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *StockQuery) FirstIDX(ctx context.Context) int {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Stock entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Stock entity is found.
// Returns a *NotFoundError when no Stock entities are found.
func (sq *StockQuery) Only(ctx context.Context) (*Stock, error) {
	nodes, err := sq.Limit(2).All(setContextOp(ctx, sq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{stock.Label}
	default:
		return nil, &NotSingularError{stock.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *StockQuery) OnlyX(ctx context.Context) *Stock {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Stock ID in the query.
// Returns a *NotSingularError when more than one Stock ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *StockQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(2).IDs(setContextOp(ctx, sq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{stock.Label}
	default:
		err = &NotSingularError{stock.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *StockQuery) OnlyIDX(ctx context.Context) int {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Stocks.
func (sq *StockQuery) All(ctx context.Context) ([]*Stock, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryAll)
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Stock, *StockQuery]()
	return withInterceptors[[]*Stock](ctx, sq, qr, sq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sq *StockQuery) AllX(ctx context.Context) []*Stock {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Stock IDs.
func (sq *StockQuery) IDs(ctx context.Context) (ids []int, err error) {
	if sq.ctx.Unique == nil && sq.path != nil {
		sq.Unique(true)
	}
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryIDs)
	if err = sq.Select(stock.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *StockQuery) IDsX(ctx context.Context) []int {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *StockQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryCount)
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sq, querierCount[*StockQuery](), sq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sq *StockQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *StockQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryExist)
	switch _, err := sq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *StockQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StockQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *StockQuery) Clone() *StockQuery {
	if sq == nil {
		return nil
	}
	return &StockQuery{
		config:     sq.config,
		ctx:        sq.ctx.Clone(),
		order:      append([]stock.OrderOption{}, sq.order...),
		inters:     append([]Interceptor{}, sq.inters...),
		predicates: append([]predicate.Stock{}, sq.predicates...),
		withStakes: sq.withStakes.Clone(),
		// clone intermediate query.
		sql:  sq.sql.Clone(),
		path: sq.path,
	}
}

// WithStakes tells the query-builder to eager-load the nodes that are connected to
// the "stakes" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *StockQuery) WithStakes(opts ...func(*StakeQuery)) *StockQuery {
	query := (&StakeClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withStakes = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ChannelID string `json:"channel_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Stock.Query().
//		GroupBy(stock.FieldChannelID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sq *StockQuery) GroupBy(field string, fields ...string) *StockGroupBy {
	sq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StockGroupBy{build: sq}
	grbuild.flds = &sq.ctx.Fields
	grbuild.label = stock.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ChannelID string `json:"channel_id,omitempty"`
//	}
//
//	client.Stock.Query().
//		Select(stock.FieldChannelID).
//		Scan(ctx, &v)
func (sq *StockQuery) Select(fields ...string) *StockSelect {
	sq.ctx.Fields = append(sq.ctx.Fields, fields...)
	sbuild := &StockSelect{StockQuery: sq}
	sbuild.label = stock.Label
	sbuild.flds, sbuild.scan = &sq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StockSelect configured with the given aggregations.
func (sq *StockQuery) Aggregate(fns ...AggregateFunc) *StockSelect {
	return sq.Select().Aggregate(fns...)
}

func (sq *StockQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sq); err != nil {
				return err
			}
		}
	}
	for _, f := range sq.ctx.Fields {
		if !stock.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *StockQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Stock, error) {
	var (
		nodes       = []*Stock{}
		_spec       = sq.querySpec()
		loadedTypes = [1]bool{
			sq.withStakes != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Stock).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Stock{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sq.withStakes; query != nil {
		if err := sq.loadStakes(ctx, query, nodes,
			func(n *Stock) { n.Edges.Stakes = []*Stake{} },
			func(n *Stock, e *Stake) { n.Edges.Stakes = append(n.Edges.Stakes, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sq *StockQuery) loadStakes(ctx context.Context, query *StakeQuery, nodes []*Stock, init func(*Stock), assign func(*Stock, *Stake)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Stock)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Stake(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(stock.StakesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.stock_stakes
		if fk == nil {
			return fmt.Errorf(`foreign-key "stock_stakes" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "stock_stakes" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (sq *StockQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	_spec.Node.Columns = sq.ctx.Fields
	if len(sq.ctx.Fields) > 0 {
		_spec.Unique = sq.ctx.Unique != nil && *sq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *StockQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(stock.Table, stock.Columns, sqlgraph.NewFieldSpec(stock.FieldID, field.TypeInt))
	_spec.From = sq.sql
	if unique := sq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sq.path != nil {
		_spec.Unique = true
	}
	if fields := sq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stock.FieldID)
		for i := range fields {
			if fields[i] != stock.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *StockQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(stock.Table)
	columns := sq.ctx.Fields
	if len(columns) == 0 {
		columns = stock.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.ctx.Unique != nil && *sq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StockGroupBy is the group-by builder for Stock entities.
type StockGroupBy struct {
	selector
	build *StockQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *StockGroupBy) Aggregate(fns ...AggregateFunc) *StockGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the selector query and scans the result into the given value.
func (sgb *StockGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sgb.build.ctx, ent.OpQueryGroupBy)
	if err := sgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StockQuery, *StockGroupBy](ctx, sgb.build, sgb, sgb.build.inters, v)
}

func (sgb *StockGroupBy) sqlScan(ctx context.Context, root *StockQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sgb.flds)+len(sgb.fns))
		for _, f := range *sgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StockSelect is the builder for selecting fields of Stock entities.
type StockSelect struct {
	*StockQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ss *StockSelect) Aggregate(fns ...AggregateFunc) *StockSelect {
	ss.fns = append(ss.fns, fns...)
	return ss
}

// Scan applies the selector query and scans the result into the given value.
func (ss *StockSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ss.ctx, ent.OpQuerySelect)
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StockQuery, *StockSelect](ctx, ss.StockQuery, ss, ss.inters, v)
}

func (ss *StockSelect) sqlScan(ctx context.Context, root *StockQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ss.fns))
	for _, fn := range ss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
