// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kkrishguptaa/whitestone-capital/apps/api/ent/schema"
	"github.com/kkrishguptaa/whitestone-capital/apps/api/ent/stock"
)

// Stock is the model entity for the Stock schema.
type Stock struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Slack channel ID for the stock.
	ChannelID string `json:"channel_id,omitempty"`
	// Stock symbol, e.g., 'AAPL' for Apple Inc.
	Symbol string `json:"symbol,omitempty"`
	// Full name of the stock, e.g., 'Apple Inc.'
	Name string `json:"name,omitempty"`
	// Activity data for the stock, including date, messages count, and users count
	Activity *schema.Activity `json:"activity,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StockQuery when eager-loading is set.
	Edges        StockEdges `json:"edges"`
	selectValues sql.SelectValues
}

// StockEdges holds the relations/edges for other nodes in the graph.
type StockEdges struct {
	// The stakes held in the stock by users
	Stakes []*Stake `json:"stakes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// StakesOrErr returns the Stakes value or an error if the edge
// was not loaded in eager-loading.
func (e StockEdges) StakesOrErr() ([]*Stake, error) {
	if e.loadedTypes[0] {
		return e.Stakes, nil
	}
	return nil, &NotLoadedError{edge: "stakes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Stock) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case stock.FieldActivity:
			values[i] = new([]byte)
		case stock.FieldID:
			values[i] = new(sql.NullInt64)
		case stock.FieldChannelID, stock.FieldSymbol, stock.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Stock fields.
func (s *Stock) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case stock.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case stock.FieldChannelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				s.ChannelID = value.String
			}
		case stock.FieldSymbol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field symbol", values[i])
			} else if value.Valid {
				s.Symbol = value.String
			}
		case stock.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				s.Name = value.String
			}
		case stock.FieldActivity:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field activity", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &s.Activity); err != nil {
					return fmt.Errorf("unmarshal field activity: %w", err)
				}
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Stock.
// This includes values selected through modifiers, order, etc.
func (s *Stock) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// QueryStakes queries the "stakes" edge of the Stock entity.
func (s *Stock) QueryStakes() *StakeQuery {
	return NewStockClient(s.config).QueryStakes(s)
}

// Update returns a builder for updating this Stock.
// Note that you need to call Stock.Unwrap() before calling this method if this Stock
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Stock) Update() *StockUpdateOne {
	return NewStockClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Stock entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Stock) Unwrap() *Stock {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Stock is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Stock) String() string {
	var builder strings.Builder
	builder.WriteString("Stock(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("channel_id=")
	builder.WriteString(s.ChannelID)
	builder.WriteString(", ")
	builder.WriteString("symbol=")
	builder.WriteString(s.Symbol)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(s.Name)
	builder.WriteString(", ")
	builder.WriteString("activity=")
	builder.WriteString(fmt.Sprintf("%v", s.Activity))
	builder.WriteByte(')')
	return builder.String()
}

// Stocks is a parsable slice of Stock.
type Stocks []*Stock
