// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Stake is the predicate function for stake builders.
type Stake func(*sql.Selector)

// Stock is the predicate function for stock builders.
type Stock func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
