// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/kkrishguptaa/whitestone-capital/apps/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// SlackID applies equality check predicate on the "slack_id" field. It's identical to SlackIDEQ.
func SlackID(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSlackID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// SlackIDEQ applies the EQ predicate on the "slack_id" field.
func SlackIDEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSlackID, v))
}

// SlackIDNEQ applies the NEQ predicate on the "slack_id" field.
func SlackIDNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldSlackID, v))
}

// SlackIDIn applies the In predicate on the "slack_id" field.
func SlackIDIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldSlackID, vs...))
}

// SlackIDNotIn applies the NotIn predicate on the "slack_id" field.
func SlackIDNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldSlackID, vs...))
}

// SlackIDGT applies the GT predicate on the "slack_id" field.
func SlackIDGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldSlackID, v))
}

// SlackIDGTE applies the GTE predicate on the "slack_id" field.
func SlackIDGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldSlackID, v))
}

// SlackIDLT applies the LT predicate on the "slack_id" field.
func SlackIDLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldSlackID, v))
}

// SlackIDLTE applies the LTE predicate on the "slack_id" field.
func SlackIDLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldSlackID, v))
}

// SlackIDContains applies the Contains predicate on the "slack_id" field.
func SlackIDContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldSlackID, v))
}

// SlackIDHasPrefix applies the HasPrefix predicate on the "slack_id" field.
func SlackIDHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldSlackID, v))
}

// SlackIDHasSuffix applies the HasSuffix predicate on the "slack_id" field.
func SlackIDHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldSlackID, v))
}

// SlackIDEqualFold applies the EqualFold predicate on the "slack_id" field.
func SlackIDEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldSlackID, v))
}

// SlackIDContainsFold applies the ContainsFold predicate on the "slack_id" field.
func SlackIDContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldSlackID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldName, v))
}

// HasStakes applies the HasEdge predicate on the "stakes" edge.
func HasStakes() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StakesTable, StakesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStakesWith applies the HasEdge predicate on the "stakes" edge with a given conditions (other predicates).
func HasStakesWith(preds ...predicate.Stake) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newStakesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
