name: Docker

on:
  push:
    paths:
      - "apps/api/**"
      - "apps/slack/**"
      - ".github/workflows/docker.yaml"
    branches:
      - main
    tags:
      - "*"

permissions:
  contents: read
  packages: write

env:
  PROJECT_NAME: whitestone-capital

jobs:
  ghcr:
    strategy:
      matrix:
        app:
          - api

    name: Publish ${{ matrix.app }} Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Login ghcr.io
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Metadata for ${{ matrix.app }}
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.PROJECT_NAME }}_${{ matrix.app }}
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
            type=sha,enable=${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
            type=ref,event=tag,enable=${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}

      - name: Build and Push ${{ matrix.app }} Docker Image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: ./apps/${{ matrix.app }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
